[package]
name = "teraclio"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
serde_json = "1.0.107"
tera = "1.19.1"
base64 = "0.21.4"